# Generated by Django 4.1.1 on 2023-04-05 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_time_now_postcomment_time_now_postlike_time_now_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='time_now',
        ),
        migrations.RemoveField(
            model_name='postcomment',
            name='time_now',
        ),
        migrations.RemoveField(
            model_name='postlike',
            name='time_now',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='time_now',
        ),
        migrations.RemoveField(
            model_name='user',
            name='time_now',
        ),
    ]
